// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,s
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Config.FIREBASE_WEB_API_KEY,
    appId: Config.FIREBASE_WEB_APP_ID,
    messagingSenderId: Config.FIREBASE_MESSAGING_SENDER_ID,
    projectId: Config.FIREBASE_PROJECT_ID,
    authDomain: Config.FIREBASE_AUTH_DOMAIN,
    storageBucket: Config.FIREBASE_STORAGE_BUCKET,
    measurementId: Config.FIREBASE_MEASUREMENT_ID,
    databaseURL: Config.FIREBASE_DATABASE_URL
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Config.FIREBASE_ANDROID_API_KEY,
    appId: Config.FIREBASE_ANDROID_APP_ID,
    messagingSenderId: Config.FIREBASE_MESSAGING_SENDER_ID,
    projectId: Config.FIREBASE_PROJECT_ID,
    storageBucket: Config.FIREBASE_STORAGE_BUCKET,
    databaseURL: Config.FIREBASE_DATABASE_URL
  );
}
